
      bconfig: {
  // Use Netlify’s “Git Gateway” authentication and target our default branch
  backend: {
    name: 'git-gateway',
    branch: 'main',
  },
  collections: [
    // Define a blog post collection
    {
      name: 'blog',
      label: 'Blog',
      folder: 'src/pages/blog',
      create: true,
      delete: true,
      fields: [
        {label: "Layout", name: "layout", widget: "hidden", default: "../../layouts/BlogPost.astro"}
       {label: "Title", name: "title", widget: "string"}
       {label: "Description", name: "description", widget: "string"}
       {label: "Publish Date", name: "publishDate", widget: "datetime"}
       {label: "Hero Imagett", name: "heroImage", widget: "image"}
       {label: "Body", name: "body", widget: "markdown"}

      ],
    },
  ],
};