backend: {
    name: 'git-gateway',
    branch: 'main',
  },

fields:
  {label: "Layout", name: "layout", widget: "hidden", default: "../../layouts/BlogPost.astro"}
       {label: "Title", name: "title", widget: "string"}
       {label: "Description", name: "description", widget: "string"}
       {label: "Publish Date", name: "publishDate", widget: "datetime"}
       {label: "Hero Imagett", name: "heroImage", widget: "image"}
       {label: "Body", name: "body", widget: "markdown"}


backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - label: "Blog"
    name: "blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
     - {label: "Layout", name: "layout", widget: "hidden", default: "../../layouts/BlogPost.astro"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Publish Date", name: "publishDate", widget: "datetime"}
      - {label: "Hero Imagett", name: "heroImage", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}

 