backend: {
    name: 'git-gateway',
    branch: 'main',
  },

fields:
  {label: "Layout", name: "layout", widget: "hidden", default: "../../layouts/BlogPost.astro"}
       {label: "Title", name: "title", widget: "string"}
       {label: "Description", name: "description", widget: "string"}
       {label: "Publish Date", name: "publishDate", widget: "datetime"}
       {label: "Hero Imagett", name: "heroImage", widget: "image"}
       {label: "Body", name: "body", widget: "markdown"}



 